name: fix_it_solutions
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

#---------------------- PACKAGES ----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  connectivity_plus: ^6.0.5
  lottie: ^3.1.2
  shimmer: ^3.0.0
  image_picker:
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  file_picker: ^5.2.0
  

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  shelf: ^1.4.1

  # Product Specific
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core:
  firebase_auth: 
  cloud_firestore:
  google_sign_in: ^6.1.6
  google_api_availability:
  provider:
  firebase_storage: ^11.5.4
  cached_network_image: ^3.4.1
  share_plus: ^10.1.2
  cross_file: ^0.3.4+2
  
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/icons/brands/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/images/animations/  
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/
    - assets/logos/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins-Italic.ttf
          style: italic
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800
        - asset: assets\fonts\Poppins-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets\fonts\Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets\fonts\Poppins-LightItalic.ttf
          weight: 300
          style: italic